<table width="100%" border="0">
	<tr>
		<td align="center" style="font-size: 30px">可替换选项</td>
	</tr>
<?php if($this->replacement_pool):?>
<?php foreach ($this->replacement_pool as $rp_key => $rp_val):?>
	<tr>
		<td align="center"><select name="contains-<?=$rp_key?>" style="font-size:25px;">
				<?php foreach ($rp_val as $product_id => $product_info):?>
					<?php
						$model_plugin = new Algorithms_Extensions_Plugin();
						$price_diff = $model_plugin->FormatPrice($product_info['price'] - $_SESSION['eat-in']['items']['sets'][$this->item_id]['contains'][$rp_key]['unit_price']);
						if(0 < $price_diff)
						{
							$extra = " +".$price_diff;
						}elseif(0 > $price_diff)
						{
							$extra = " ".$price_diff;
						}else{
							$extra = "";
						}
					?>
					
					<option value="<?=$product_id?>" <?php if($product_id==$this->initial_contains[$rp_key]){echo "selected='selected'";}?>><?php echo $product_info['name'].$extra;?></option>
				<?php endforeach;?>
				</select>
			</td>
		</tr>
	<?php endforeach;?>
<?php endif;?>
	<tr>
		<td align="center" style="font-size: 30px">提交</td>
	</tr>
</table>