<div id="eatinbar"><strong>主食</strong>
<div id="eatinicon">
  <ul>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>1</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>2</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>3</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>4</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>5</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>6</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>7</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>8</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>9</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>10</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>11</strong></a></li>
  </ul>
</div>
</div>

<script>
function onBridgeReady(){
    document.addEventListener('WeixinJSBridgeReady', function onBridgeReady()  {
		WeixinJSBridge.call('hideOptionMenu');
		});
}
</script>