<div id="eatinbar"><div style="font-size: 75px; font-weight:900;">套餐</div>
<div id="eatinicon">
  <ul>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>801</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>802</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>803</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>804</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>805</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>806</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>807</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>808</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>809</strong></a></li>
  </ul>
</div>
</div>
<div id="eatinbar"><div style="font-size: 75px; font-weight:900;">主食</div>
<div id="eatinicon">
  <ul>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>1</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>2</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>3</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>4</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>5</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>6</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>7</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>8</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>9</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>10</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>11</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>12</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>13</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>14</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>15</strong></a></li>
  </ul>
</div>
</div>
<div id="eatinbar"><div style="font-size: 75px; font-weight:900;">酒水饮料</div>
<div id="eatinicon">
  <ul>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>16</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>17</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>18</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>19</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>20</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>21</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>22</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>23</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>24</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>25</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>26</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>27</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>28</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>29</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>30</strong></a></li>
  </ul>
</div>
</div>
<div id="bottomNav">
<table width="100%" border="0">
<tr>
<td><img src="/images/icons/trash2.png" border="0" alt="废弃订单" /></td>
<td align="right" style="font-size: 75px; color: white;">(3)件:￥65.00</td>
</tr>
</table>

</div>