<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
	<title>Mandarin Garden</title>	
	<script src="/scripts/jquery-1.10.2.js"></script>
	<link rel="stylesheet" type="text/css" href="/styles/default/default.css" />
	<meta http-equiv="Content-type" content="text/html; charset=UTF-8" />
</head>
<body onload="onBridgeReady()">
<div id="eatinbar"><strong>主食</strong>
<div id="eatinicon">
  <ul>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>1</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>2</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>3</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>4</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>5</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>6</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>7</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>8</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>9</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>10</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>11</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>311</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>811</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>881</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>811</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>181</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>118</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>811</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>1</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>2</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>3</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>4</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>5</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>6</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>7</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>8</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>9</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>10</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>11</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>311</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>811</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>881</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>811</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>181</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>118</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>811</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>1</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>2</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>3</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>4</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>5</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>6</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>7</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>8</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>9</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>10</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>11</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>311</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>811</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>881</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>811</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>181</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>118</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>811</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>1</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>2</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>3</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>4</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>5</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>6</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>7</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>8</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>9</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>10</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>11</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>311</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>811</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>881</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>811</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>181</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>118</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>811</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>1</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>2</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>3</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>4</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>5</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>6</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>7</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>8</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>9</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>10</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>11</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>311</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>811</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>881</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>811</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>181</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>118</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>811</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>1</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>2</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>3</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>4</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>5</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>6</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>7</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>8</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>9</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>10</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>11</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>311</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>811</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>881</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>811</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>181</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>118</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>811</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>1</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>2</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>3</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>4</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>5</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>6</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>7</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>8</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>9</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>10</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>11</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>311</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>811</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>881</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>811</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>181</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>118</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>811</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>1</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>2</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>3</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>4</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>5</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>6</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>7</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>8</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>9</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>10</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>11</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>311</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>811</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>881</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>811</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>181</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>118</strong></a></li>
		<li><a href="/eat-in/add-item/type/product/id/"><strong>811</strong></a></li>
  </ul>
</div>
</div>

<script>
function onBridgeReady(){
    document.addEventListener('WeixinJSBridgeReady', function onBridgeReady()  {
		WeixinJSBridge.call('hideOptionMenu');
		});
}
</script>
</body>
</html>