<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
	<link rel="SHORTCUT ICON" href="/images/favicon.ico">
	<link rel="stylesheet" type="text/css" href="/styles/default/default.css">
	<meta http-equiv="Content-type" content="text/html; charset=UTF-8">
	<title><?=$this->title?> - <?=$this->system_name?></title>	
</head>
<frameset rows="40,*" frameborder="no" border="0" framespacing="0">
  <frame src="/eat-in/topbar" name="topbarFrame" scrolling="no" noresize="noresize" id="topbarFrame" />
  <frameset name="mainFrame" cols="240,*" frameborder="0" framespacing="0" id="mainFrame">
      <frame src="/eat-in/leftbar"  scrolling="auto" noresize="noresize" id="leftbarFrame" name="leftbarFrame" />
      <frame src="/eat-in/rightzone"  scrolling="auto" noresize="noresize" id="rightFrame" name="rightFrame" />
  </frameset>
</frameset>
</html>