<table width="100%" border="0">
	<tr align="center" height="200">
		<td colspan="3" style="font-size: 50px">编辑已选套餐</td>
	</tr>
	<tr align="left">
		<td colspan="3" style="font-size: 30px">可替换商品</td>
	</tr>
	<?php if($this->replacement_pool):?>
	<?php foreach ($this->replacement_pool as $rp_key => $rp_val):?>
		<tr>
			<td align="right" style="font-size: 30px"><?=$_SESSION['eat-in']['items']['sets'][$this->item_id]['contains'][$rp_key]['product_name']?></td>
			<td align="center" style="font-size: 30px"> -> </td>
			<td align="left" style="font-size: 30px">
				<select name="update-item" style="font-size:25px;" onchange="javascript:location.href=this.value;">
					<option>--可替换商品--</option>
				<?php foreach ($rp_val as $product_id => $product_info):?>
					<?php if($_SESSION['eat-in']['items']['sets'][$this->item_id]['contains'][$rp_key]['product_id'] != $product_id):?>
					<?php
						$model_plugin = new Algorithms_Extensions_Plugin();
						$price_diff = $model_plugin->FormatPrice($product_info['price'] - $_SESSION['eat-in']['items']['sets'][$this->item_id]['contains'][$rp_key]['unit_price']);
						if(0 < $price_diff)
						{
							$extra = " +".$price_diff;
						}elseif(0 > $price_diff)
						{
							$extra = " ".$price_diff;
						}else{
							$extra = "";
						}
					?>
					
					<option value="/eat-in/update-sets-submit/item_id/<?=$this->item_id?>/act/upd/conid/<?=$rp_key?>/newpro/<?=$product_id?>"><?php echo $product_info['name'].$extra;?></option>
					<?php endif;?>
				<?php endforeach;?>
				</select>
			</td>
		</tr>
	<?php endforeach;?>
	<?php endif;?>

	<?php if($this->msg):?>
	<tr align="center">
		<td colspan="3" style="font-size: 30px;color:#ff0000">* <?=$this->msg?></td>
	</tr>
	<?php endif;?>
	<tr align="center" valign="middle" height="200">
		<td colspan="3" style="font-size: 30px"><a href="/eat-in/update-sets-submit/item_id/<?=$this->item_id?>/act/del" target="_self" class="huge red awesome">删除套餐</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="/eat-in/rightzone" target="_self" class="large yellow awesome">返回点餐页</a></td>
	</tr>
</table>