<style>
td {
	 font-size: 40px;
}
</style>
<h3>分类占比</h3>
<canvas id="category-pie" data-type="Pie" width="100%"></canvas>
<br /><br />
<h3>单品销售排名 Top50</h3>
<table width="100%" border="0" cellpadding="1" cellspacing="1">
	<tr>
		<td align="center">排名</td>
		<td align="center">销售量</td>
		<td align="center">销售额</td>
		<td align="center">名称</td>
	</tr>
	<?php if($this->data):?>
	<?php $n = 1;?>
	<?php foreach($this->data as $data):?>
	<tr bgcolor="<?php if(1 == $n%2){echo "#9F9DAB";}else{echo "#D5D8CD";}?>">
		<td align="center"><?=$n?></td>
		<td align="center"><?=$data['qty']?></td>
		<td align="center"><?=$data['price']?></td>
		<td align="center"><?=$data['ritem_name']?></td>
	</tr>
	<?php $n += 1;?>
	<?php if(50 < $n){break;}?>
	<?php endforeach;?>
	<?php endif;?>
</table>
<br /><br />
类别：<select name="category" onchange="javascript:location.href=this.value;">
<option value="/reports/si?category=0<?php if($this->date_from){echo "&date_from=".$this->date_from;}?><?php if($this->date_to){echo "&date_to=".$this->date_to;}?><?php if($this->orderby){echo "&orderby=".$this->orderby;}?>">全部</option>
<?php if($this->categories):?>
<?php foreach($this->categories as $cat_key => $cat_val):?>
<option value="/reports/si?category=<?=$cat_key?><?php if($this->date_from){echo "&date_from=".$this->date_from;}?><?php if($this->date_to){echo "&date_to=".$this->date_to;}?><?php if($this->orderby){echo "&orderby=".$this->orderby;}?>" <?php if($cat_key==$this->category){echo "selected='selected'";}?>><?=$cat_val?></option>
<?php endforeach;?>
<?php endif;?>
</select><br /><br />
排序：<select name="orderby" onchange="javascript:location.href=this.value;">
<option value="/reports/si?orderby=qty<?php if($this->date_from){echo "&date_from=".$this->date_from;}?><?php if($this->date_to){echo "&date_to=".$this->date_to;}?><?php if($this->category){echo "&category=".$this->category;}?>" <?php if('qty'==$this->orderby){echo "selected='selected'";}?>>销售量</option>
<option value="/reports/si?orderby=amount<?php if($this->date_from){echo "&date_from=".$this->date_from;}?><?php if($this->date_to){echo "&date_to=".$this->date_to;}?><?php if($this->category){echo "&category=".$this->category;}?>" <?php if('amount'==$this->orderby){echo "selected='selected'";}?>>销售额</option>
</select><br /><br />
<a href="/reports/si?date_from=<?php echo date("Y-m-d", mktime(0, 0, 0, date("m")  , date("d")-1, date("Y")));?><?php if($this->date_to){echo "&date_to=".$this->date_to;}?><?php if($this->category){echo "&category=".$this->category;}?><?php if($this->orderby){echo "&orderby=".$this->orderby;}?>" class="middle blue awesome">近1天</a>&nbsp;&nbsp;
<a href="/reports/si?date_from=<?php echo date("Y-m-d", mktime(0, 0, 0, date("m")  , date("d")-7, date("Y")));?><?php if($this->date_to){echo "&date_to=".$this->date_to;}?><?php if($this->category){echo "&category=".$this->category;}?><?php if($this->orderby){echo "&orderby=".$this->orderby;}?>" class="middle blue awesome">近7天</a>&nbsp;&nbsp;
<a href="/reports/si?date_from=<?php echo date("Y-m-d", mktime(0, 0, 0, date("m")-1  , date("d"), date("Y")));?><?php if($this->date_to){echo "&date_to=".$this->date_to;}?><?php if($this->category){echo "&category=".$this->category;}?><?php if($this->orderby){echo "&orderby=".$this->orderby;}?>" class="middle blue awesome">近30天</a>
<br /><br />

<script src="/scripts/prettify.js"></script>
<script src="/scripts/Chart.min.js"></script>
<script>
var data = [<?=$this->pie?>];

var ctx = document.getElementById("category-pie").getContext("2d");
new Chart(ctx).Pie(data);
</script>