<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
	<title>Mandarin Garden</title>	
	<script src="/scripts/jquery-1.10.2.js"></script>
	<link rel="stylesheet" type="text/css" href="/styles/default/default.css" />
	<meta http-equiv="Content-type" content="text/html; charset=UTF-8" />
</head>
<body onload="onBridgeReady()">
<?php echo $this->layout()->content; ?>
</body>
</html>
